fix: breaking changes are now recognized as meaningful
JoshuaKGoldberg/should-semantic-release pull request #140
Opened 2023-12-03 01:23 UTC by steveluscher

Closes #139.

2023-12-04 16:36 UTC, JoshuaKGoldberg requested changes
🚀 A good start, thanks for getting it going! Left a few points of discussion - what do you think?

2023-12-04 16:36 UTC, JoshuaKGoldberg commented on src/getCommitMeaning.ts
> +		/* empty */
[Refactor] I'm not a big fan of `try`/`catch` as a control flow concept. It's not type-safe, is hard to mentally model, and can accidentally wrap around unintentionally throwing code too. Let's restrict what's being wrapped to just the `toConventionalChangelogFormat` call.

2023-12-04 16:36 UTC, JoshuaKGoldberg commented on src/getCommitMeaning.ts
> +} from "@conventional-commits/parser";
[Refactor] 🤔 `@conventional-commits/parser` hasn't had a commit or sustained GitHub issue triage in 3 years, and uses `throw` as a form of control flow. Whereas `conventional-commits-parser` released 3 months ago. I'm a little averse to going down to an older, less-maintained package if it's avoidable.

What do you think about instead using a small regex to check for a subject, optionally an area/scope, and `!` at the beginning? `/^\w+(\(\w+\))?!:/` or something like that?

2023-12-04 16:36 UTC, JoshuaKGoldberg commented on src/getCommitMeaning.test.ts
> +		["style: bump\n\nBREAKING-CHANGE: breaks things", "meaningful"],
[Testing] Thinking about test edge cases...

* `!` in the commit body (so not a breaking/meaningful change)
* Footer note other than `BREAKING CHANGE`
* Multiple footer notes

2023-12-04 16:36 UTC, JoshuaKGoldberg commented on src/getCommitMeaning.test.ts
> +		// Breaking changes are meaningful no matter the type of the commit.
[Style] Just nitpicking here, I think the comment is explanatory from the test cases.

```suggestion
```

2023-12-16 00:14 UTC, steveluscher commented
This is all great feedback! Thanks for taking the time to go over it.

I'm going to step away from this PR though instead of finishing it up.

![giphy](https://github.com/JoshuaKGoldberg/should-semantic-release/assets/13243/62d1035d-f0c3-4cfb-99b6-70ad4f3888b9)

2023-12-16 00:14 UTC, closed without merging